name: merge to main workflow

on:
  push:
    branches: [main]

permissions: {}
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@bda627e2ce1a32ea56bcc815aec57b06cfa63c9d
    permissions:
      attestations: read
      contents: read
      packages: read
    with:
      verify_published_from_main_image: true
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@bda627e2ce1a32ea56bcc815aec57b06cfa63c9d
    needs: [get_config_values]
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  tag_release:
    needs: [quality_checks, get_commit_id, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@889349f9d93e4846a642f7973b7c26b180bec5aa
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      dry_run: true
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}

  package_code:
    needs: [get_commit_id, tag_release, get_config_values]
    uses: ./.github/workflows/cdk_package_code.yml
    permissions:
      contents: read
      packages: read
      id-token: write
    with:
      BRANCH_NAME: main
      VERSION_NUMBER: ${{ needs.tag_release.outputs.version_tag }}
      COMMIT_ID: ${{ needs.get_commit_id.outputs.commit_id }}
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}

  release_dev:
    needs: [get_commit_id, tag_release, package_code, get_config_values]
    uses: ./.github/workflows/cdk_release_code.yml
    permissions:
      contents: write
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      BRANCH_NAME: main
      STACK_NAME: cpt-api
      AWS_ENVIRONMENT: dev
      APIGEE_ENVIRONMENT: internal-dev
      VERSION_NUMBER: ${{ needs.tag_release.outputs.version_tag }}
      COMMIT_ID: ${{ needs.get_commit_id.outputs.commit_id }}
      CDK_APP_NAME: CptsApiApp
      LOG_RETENTION_IN_DAYS: 30
      LOG_LEVEL: DEBUG
      TRUSTSTORE_FILE: clinical-tracker-truststore.pem
      RUN_REGRESSION_TESTS: true
      IS_PULL_REQUEST: false
      FORWARD_CSOC_LOGS: false
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
      PROXYGEN_ROLE: ${{ secrets.PROXYGEN_PTL_ROLE }}
      TARGET_SPINE_SERVER: ${{ secrets.DEV_TARGET_SPINE_SERVER }}
      REGRESSION_TESTS_PEM: ${{ secrets.REGRESSION_TESTS_PEM }}
      APIM_STATUS_API_KEY: ${{ secrets.APIM_STATUS_API_KEY }}

  # release_dev_sandbox:
  #   needs: [get_commit_id, tag_release, package_code, release_dev]
  #   uses: ./.github/workflows/cdk_release_code.yml
  #   with:
  #     BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}
  #     STACK_NAME: cpt-api-sandbox
  #     AWS_ENVIRONMENT: dev
  #     APIGEE_ENVIRONMENT: internal-dev-sandbox
  #     VERSION_NUMBER: ${{ needs.tag_release.outputs.version_tag }}
  #     COMMIT_ID: ${{ needs.get_commit_id.outputs.commit_id }}
  #     CDK_APP_NAME: CptsApiSandboxApp
  #     LOG_RETENTION_IN_DAYS: 30
  #     LOG_LEVEL: DEBUG
  #     TRUSTSTORE_FILE: clinical-tracker-sandbox-truststore.pem
  #   secrets:
  #     CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
  #     PROXYGEN_ROLE: ${{ secrets.PROXYGEN_PTL_ROLE }}
  #     TARGET_SPINE_SERVER: sandbox
  #     REGRESSION_TESTS_PEM: ${{ secrets.REGRESSION_TESTS_PEM }}
  #     APIM_STATUS_API_KEY: ${{ secrets.APIM_STATUS_API_KEY }}

  release_qa:
    needs: [get_commit_id, tag_release, package_code, release_dev, get_config_values] # TODO: add sandbox back once implemented
    uses: ./.github/workflows/cdk_release_code.yml
    permissions:
      contents: write
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      BRANCH_NAME: main
      STACK_NAME: cpt-api
      AWS_ENVIRONMENT: qa
      APIGEE_ENVIRONMENT: internal-qa
      VERSION_NUMBER: ${{ needs.tag_release.outputs.version_tag }}
      COMMIT_ID: ${{ needs.get_commit_id.outputs.commit_id }}
      CDK_APP_NAME: CptsApiApp
      LOG_RETENTION_IN_DAYS: 30
      LOG_LEVEL: DEBUG
      TRUSTSTORE_FILE: clinical-tracker-truststore.pem
      RUN_REGRESSION_TESTS: true
      IS_PULL_REQUEST: false
      FORWARD_CSOC_LOGS: false
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.QA_CLOUD_FORMATION_DEPLOY_ROLE }}
      PROXYGEN_ROLE: ${{ secrets.PROXYGEN_PTL_ROLE }}
      TARGET_SPINE_SERVER: ${{ secrets.QA_TARGET_SPINE_SERVER }}
      REGRESSION_TESTS_PEM: ${{ secrets.REGRESSION_TESTS_PEM }}
      APIM_STATUS_API_KEY: ${{ secrets.APIM_STATUS_API_KEY }}
